version: '3'

services:
  simket:
    container_name: sk
    build:
      context: .
      dockerfile: Dockerfile
    image: simket
    volumes:
        - ..:/work/simket
    ports:
        - "8888:8888"
